author: Katie Leatherman
title: Katie Leatherman
plugins: 
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-gist
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

include:
  - "subject-colors/assets/_initCloneObject-700ScFCJ.js"
  - "subject-colors/assets/_baseSet-DehVzRp6.js"
  - "subject-colors/assets/_hasPath-D0QK37mF.js"
  - "subject-colors/assets/__vite-browser-external-DeX3BBVP.js"
  - "subject-colors/assets/__vite-browser-external-mTzvI0UM.js"