author: Katie Leatherman
title: Katie Leatherman
plugins: 
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-gist
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dirt"